#!/usr/bin/env bash

[ -z "$GITHUB_ENV" ] || . $GITHUB_ENV

curl -X DELETE https://api.github.com/repos/pfapi/cicd-test/branches/main/protection \
  -H "Accept: application/vnd.github.luke-cage-preview+json" \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Content-Type: application/json" \
  --data-binary @- <<DATA
{
  "required_status_checks": null,
  "enforce_admins": false,
  "required_pull_request_reviews": null,
  "required_linear_history": true,
  "allow_force_pushes": false,
  "allow_deletions": false,
  "required_conversation_resolution": false,
  "restrictions": null
}
DATA